apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: platforms
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: examplepass
        ports:
        - containerPort: 5432
        # small ephemeral volume (ok para laboratorio)
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        emptyDir: {}

