apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: platforms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        # simple static page so ingress shows something
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
      - name: www
        emptyDir: {}
---
# init pod to create a simple index.html (only for demo in k8s, optional)
apiVersion: v1
kind: Pod
metadata:
  name: frontend-init
  namespace: platforms
  labels:
    app: frontend-init
spec:
  restartPolicy: Never
  containers:
  - name: create-index
    image: busybox
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /work && echo "<h1>Frontend - hit from ingress</h1><p>Try: curl / on backend service</p>" > /work/index.html && sleep 1
    volumeMounts:
      - name: www
        mountPath: /work
  volumes:
    - name: www
      emptyDir: {}

